//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package cz.destil.feelings.ui;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import com.googlecode.androidannotations.api.SdkVersionHelper;
import cz.destil.feelings.R.id;
import cz.destil.feelings.R.layout;

public final class NewFeelingActivity_
    extends NewFeelingActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_new_feeling);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        {
            View view = findViewById(id.feeling0);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    public void onClick(View view) {
                        feelingClicked(view);
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.feeling1);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    public void onClick(View view) {
                        feelingClicked(view);
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.feeling2);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    public void onClick(View view) {
                        feelingClicked(view);
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.feeling3);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    public void onClick(View view) {
                        feelingClicked(view);
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.feeling4);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    public void onClick(View view) {
                        feelingClicked(view);
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.feeling5);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    public void onClick(View view) {
                        feelingClicked(view);
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.feeling6);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    public void onClick(View view) {
                        feelingClicked(view);
                    }

                }
                );
            }
        }
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static NewFeelingActivity_.IntentBuilder_ intent(Context context) {
        return new NewFeelingActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, NewFeelingActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public NewFeelingActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

    }

}
